# Where things are
source:             ./
destination:        _site
build:              _build

# Relative to source
data_dir:           _data
posts_dir:          _posts
drafts_dir:         _drafts
scripts_dir:        _scripts
styles_dir:         _styles
images_dir:         _images
sprites_dir:        _sprites
templates_dir:      _templates

# Collections
# collections:
#   cartoons:
#     layout:     default
#     output:     true

# Handling Reading
encoding:           utf-8
markdown_ext:       markdown,mkdown,mkdn,mkd,md
html_ext:           html,htm

# Filtering Content
show_drafts:        null
future:             false
unpublished:        false

# Plugins
plugins:
  - velvet-plugin-paginate

# Conversion
markdown:           markdown-it

# Serving
detach:             false
port:               4000
host:               127.0.0.1
url:                {SLUSH{=url}}
staging_url:        {SLUSH{ if (staging) { print (stagingUrl) } }}
baseurl:            /
error:              error.html
single_page:        {SLUSH{ if (spa) { print(true) } else { print(false) } }} # If true, all 404s will be redirect to the index

{SLUSH{ if (github) { }}
# Releaser
github_token:       {SLUSH{=githubToken}}
{SLUSH{ } }}

{SLUSH{ if (deployer === 'ftp') { }}
# Deployer
deployer:
  type:             ftp
  host:             {SLUSH{=ftpHost}}
  directory:        {SLUSH{=ftpDirectory}}
{SLUSH{ } else if (deployer === 'aws') { }}
# Deployer
deployer:
  type:             aws
  bucket:           {SLUSH{ if (awsBucket) { print(awsBucket) } }}
{SLUSH{ } }}

# Outputting
images_path:        assets/images
scripts_path:       assets/scripts
styles_path:        assets/styles
sprites_path:       assets/sprites

timezone:           {SLUSH{=timezone}}
permalink:          pretty

# Markdown Processors
markdown-it:
  options:          commonmark
  plugins:
    -
      name:         markdown-it-implicit-figures
      options:
        dataType:   true
        figcaption: true

html:
  minify:
    envs:           [production]

styles:
  autoprefixer:     last 2 versions
  minify:
    envs:           [production]
  revision:
    envs:           [production]
{SLUSH{ if (framework === 'bootstrap') { }}
  sass:
    importMappings:
      -
        search:     ^bootstrap/(.+)
        replace:    node_modules/bootstrap/scss/$1
{SLUSH{ } else if (framework === 'starter-kit') { }}
  sass:
    importMappings:
      -
        search:     ^breakpoint$
        replace:    node_modules/breakpoint-sass/stylesheets/breakpoint
      -
        search:     ^bourbon$
        replace:    node_modules/bourbon/app/assets/stylesheets/bourbon
  postcss:
    plugins:
      - name:       lost
{SLUSH{ } }}

images:
  revision:
    envs:           [production]

scripts:
  minify:
    envs:           [production]
  revision:
    envs:           [production]

defaults:
  -
    scope:
      type:         posts
    values:
      layout:       default
  -
    scope:
      type:         pages
    values:
      layout:       default
  -
    scope:
      type:         images
    values:
      permalink:    /:urlpath/:dirname/:basename-:filters_hash:extname
  -
    scope:
      type:         scripts
    values:
      permalink:    /:urlpath/:dirname/:basename:output_ext
  -
    scope:
      type:         styles
    values:
      permalink:    /:urlpath/:dirname/:basename:output_ext
